# Generated by Django 5.1.6 on 2025-09-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='blacklisted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='admin',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='blacklisted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blacklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
