# Generated by Django 5.1.6 on 2025-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_blacklisted_at_blacklist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number (only accepted ID proof)', max_length=12, null=True, unique=True, verbose_name='Aadhar Card Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit Indian mobile number', max_length=15, null=True),
        ),
    ]
