# Generated by Django 5.1.6 on 2025-08-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_full_name_user_id_proof'),
        ('prison_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prison_core.jail'),
        ),
    ]
