# Generated by Django 5.1.6 on 2025-10-01 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_aadhar_number_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_authorize_emergency_visits',
            field=models.BooleanField(default=False, help_text='Can this user authorize emergency visits for family members'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_family_member',
            field=models.ForeignKey(blank=True, help_text='Primary family member who can authorize emergency visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_to_primary',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('other', 'Other')], help_text='Your relationship to the primary family member', max_length=20, null=True),
        ),
    ]
