# Generated by Django 5.1.6 on 2025-10-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_can_authorize_emergency_visits_and_more'),
        ('prison_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_prisoner',
            field=models.ForeignKey(blank=True, help_text='Select the prisoner you are related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='prison_core.prisoner', verbose_name='Related Prisoner'),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_to_prisoner',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse/Husband/Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('son_in_law', 'Son-in-law'), ('daughter_in_law', 'Daughter-in-law'), ('father_in_law', 'Father-in-law'), ('mother_in_law', 'Mother-in-law'), ('other', 'Other Relative')], help_text='Your relationship to the prisoner', max_length=20, null=True, verbose_name='Relationship to Prisoner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_to_primary',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse/Husband/Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('son_in_law', 'Son-in-law'), ('daughter_in_law', 'Daughter-in-law'), ('father_in_law', 'Father-in-law'), ('mother_in_law', 'Mother-in-law'), ('other', 'Other Relative')], help_text='Your relationship to the primary family member', max_length=20, null=True),
        ),
    ]
