# Generated by Django 5.1.6 on 2025-08-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Visit'), ('EMERGENCY', 'Emergency Visit')], default='REGULAR', max_length=10),
        ),
    ]
